Fix/RLP-823/signed-unlock
rsksmart/lumino pull request #130
Opened 2020-10-08 17:13 UTC by mauricioirace

Changes:
- Added signature check to prevent unlock transaction to be sent twice

NOTES: Not yet tested

2020-10-09 16:07 UTC, JONAF2103 requested changes
I see a lot of changes that are from another PR, please update this with develop content first to get rid of the extra changes that are not related to this

2020-10-09 16:07 UTC, JONAF2103 commented on raiden/api/rest.py
> +                errors="Failed trying to settle a channel that's already settled",
All these changes are from another already merged PR, be careful with this.

2020-10-09 16:07 UTC, JONAF2103 commented on raiden/api/v1/encoding.py
> +    internal_msg_identifier = fields.Integer(required=True)
Same here

2020-10-09 16:07 UTC, JONAF2103 commented on raiden/api/webui/static/endpointConfig.js
> +const nodeAddress = '0x66335087fF02A82d50b9fd81aC268c56c8aE263a';
Remove this change

2020-10-09 16:07 UTC, JONAF2103 commented on raiden/lightclient/handlers/light_client_message_handler.py
> +    def update_offchain_light_client_protocol_message_set_signed_message(
Same here, another PR has this already merged on develop

2020-10-12 15:48 UTC, mauricioirace commented on raiden/api/v1/encoding.py
> +    internal_msg_identifier = fields.Integer(required=True)
There are no changes in this lines

2020-10-12 19:05 UTC, JONAF2103 requested changes
LGTM in general but you need to fix a typo that you have there before i can approve this

2020-10-12 19:05 UTC, JONAF2103 commented on raiden/api/rest.py
> +            self.raiden_api.register_secret_light(signed_tx)git merg
Typo?

2020-10-12 19:12 UTC, JONAF2103 approved these changes
LGTM

2020-10-12 19:34 UTC, mortelli approved these changes

2020-10-12 19:35 UTC, merged