RLP-1037: invoice minimum amount
rsksmart/lumino pull request #221
Opened 2021-03-04 21:14 UTC by mortelli

This PR implements [RLP-1037](https://jirainfuy.atlassian.net/browse/RLP-1037), which is not allowing generation of an invoice with more precision than a 1p BTC or its equivalent in ETH/token, as defined in [BOLT #11](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md).

2021-03-04 22:03 UTC, mortelli commented on raiden/billing/invoices/encoder/invoice_encoder.py
> +            raise ValueError("cannot generate invoice, amount {} is too low to comply with BOLT #11".format(
my reasoning for this change:

the RFC specifies that the `p` multiplier is the smallest unit that can be used for the invoice amount.

based on this i assume that `1p` is the lowest amount allowed. this translates to `0.000000000001` BTC for the lightning network—for our case it would be ETH or token units.

therefore, if `amount = 0.000000000001` (i.e. `1p`):

1. `bool(amount * 10 ** 12 % 10) == True`, which means the minimum amount will raise a `ValueError`
2. `bool(amount * 10 ** 13 % 10) == False`, which means the minimum amount will be allowed

moreover, if `amount = 0.0000000000001` (i.e. more precision than `1p`), then: 

```
bool(amount * 10 ** 13 % 10) == True
```

which i believe is the correct behavior.

2021-03-04 22:03 UTC, mortelli commented
@JONAF2103 @marcosmartinez7 @mauricioirace 

please help me out in testing the API manually to make sure all scenarios are covered before moving this to QA (specifically: not allowing invalid amounts based on [BOLT #11](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md))

thanks :pray:

2021-03-04 22:13 UTC, marcosmartinez7 requested changes

2021-03-04 22:13 UTC, marcosmartinez7 commented on raiden/billing/invoices/encoder/invoice_encoder.py
> +            raise ValueError("cannot generate invoice, amount {} is too low to comply with BOLT #11".format(
There is a problem with this: 

```
100000.000000001 *10 ** 13 % 10
4.0

```
I dont think the mod approach will work, or at least the falsy/true evaluation. 

I think we need, assuming BTC/ETH amounts, parse the decimal part and compare against the max presition of bitcoin

In a future, if we use satoshis, milisatoshis, etc, into the encoded amount (like 1000000p) that must be refactored.

2021-03-04 22:20 UTC, mortelli commented on raiden/billing/invoices/encoder/invoice_encoder.py
> +            raise ValueError("cannot generate invoice, amount {} is too low to comply with BOLT #11".format(
you're right, this case will be a problem as well.

i'll take your suggestion into consideration and propose an alternative

2021-03-05 13:34 UTC, mortelli commented on raiden/billing/invoices/encoder/invoice_encoder.py
> +            raise ValueError("cannot generate invoice, amount {} is too low to comply with BOLT #11".format(
@marcosmartinez7 

found and implemented [this solution](https://stackoverflow.com/a/6190291), lmk what you think

2021-03-05 14:00 UTC, JONAF2103 reviewed
LGTM i will test this to approve it later

2021-03-05 14:22 UTC, JONAF2103 approved these changes
It works ok for me, approved!

2021-03-05 14:27 UTC, mauricioirace commented on raiden/billing/invoices/encoder/invoice_encoder.py
> +            raise ValueError("cannot generate invoice, amount {} is too low to comply with BOLT #11".format(
@marcosmartinez7 Agree with that approach. 
@mortelli I think it will work

2021-03-05 15:11 UTC, marcosmartinez7 approved these changes

2021-03-05 17:16 UTC, mauricioirace approved these changes
LGTM! just take into accounts the issues that can happen due to floating point limited precission.

2021-03-05 17:22 UTC, merged