RLP-671 PyLint Bugs
rsksmart/lumino pull request #76
Opened 2020-02-25 20:36 UTC by JONAF2103

* Fixing optional arguments
* Fixing missing dictionary elements
* Fixing bad function calls

2020-02-25 21:53 UTC, marcosmartinez7 requested changes
We should test the light client payments in order to validate the changes.

2020-02-25 21:53 UTC, marcosmartinez7 commented on raiden/transfer/mediated_transfer/events.py
> +            "message": str(self.message),
For the message field, since it is an istance of the `Message ` class we should use the `to_dict `hook for serialization

2020-02-25 21:53 UTC, marcosmartinez7 commented on raiden/transfer/mediated_transfer/events.py
> +            message=data["message"],
Can we use `Message.from_dict` here?

2020-02-25 21:53 UTC, marcosmartinez7 commented on raiden/transfer/mediated_transfer/events.py
> +            message_type=data["message_type"]
We should convert to the `LightClientProtocolMessageType ` enum type, otherwise the object is instanciated with an string.

2020-02-25 21:53 UTC, marcosmartinez7 commented on raiden/transfer/mediated_transfer/events.py
> +            "sender": self.sender
Here we use   ` "sender": to_checksum_address(self.sender),` in order to persist the address in the same way always.

2020-02-25 21:53 UTC, marcosmartinez7 commented on raiden/transfer/mediated_transfer/events.py
> +            sender=data["sender"]
We should use           `  sender=to_canonical_address(data["sender"]),` here to create a normalized address of type bytes

2020-02-26 14:51 UTC, marcosmartinez7 reviewed
Lgtm, but lets test the light client interaction.

2020-02-26 14:51 UTC, marcosmartinez7 commented on .gitignore
> +/raiden/api/webui/static/endpointConfig.js
Thanks :)

2020-02-26 14:51 UTC, marcosmartinez7 commented on raiden/transfer/mediated_transfer/events.py
> +            message=Message.from_dic(data["message"]),
There is a typo here on `from_dic`

2020-02-26 19:27 UTC, marcosmartinez7 approved these changes
utACK

2020-02-26 20:34 UTC, JONAF2103 commented on raiden/transfer/mediated_transfer/events.py
> +            message=Message.from_dic(data["message"]),
Solved

2020-02-26 21:15 UTC, merged